#!/usr/bin/env bash

only_staged="only-staged"
all_tracked="all-only-tracked"
all_untracked="all-include-untracked"

COMMAND="git diff --staged --name-status"
TYPE=$only_staged
 
while getopts ":aA" opt; do
  case $opt in
    a)
      COMMAND="git status --porcelain -uno"
      TYPE=$all_tracked
      ;;
    A)
      COMMAND="git status --porcelain -uall"
      TYPE=$all_untracked
      ;;
  esac
done

COMMIT_MSG=$($COMMAND | awk '
BEGIN {
  updatedCount = 0;
  addedCount = 0;
  deletedCount = 0;
}
$1 == "M" {
  updated[updatedCount] = $2;
  updatedCount += 1
}
$1 == "A" || $1 == "??" {
  added[addedCount] = $2;
  addedCount += 1
}
$1 == "D" {
  deleted[deletedCount] = $2;
  deletedCount += 1
}
END {
  if (updatedCount > 0) {
    updatedMsg = "";
    for (i = 0; i + 1 < updatedCount; i++) {
      updatedMsg = updatedMsg updated[i] ", "
    };
    updatedMsg = updatedMsg updated[updatedCount - 1]
    updatedMsg = "Update " updatedMsg
  }

  if (addedCount > 0) {
    addedMsg = "";
    for (i = 0; i + 1 < addedCount; i++) {
      addedMsg = addedMsg added[i] ", "
    };
    addedMsg = addedMsg added[addedCount - 1]
    addedMsg = "Add " addedMsg
  }

  if (deletedCount > 0) {
    deletedMsg = "";
    for (i = 0; i + 1 < deletedCount; i++) {
      deletedMsg = deletedMsg deleted[i] ", "
    };
    deletedMsg = deletedMsg deleted[deletedCount - 1]
    deletedMsg = "Delete " deletedMsg
  }

  changesCount = 0;

  if (updatedCount > 0) {
    changesCount += 1
  }

  if (addedCount > 0) {
    changesCount += 1
  }

  if (deletedCount > 0) {
    changesCount += 1
  }

  if (changesCount > 1) {
    printf "Several changes\n\n"

    if (updatedCount > 0) {
      print updatedMsg
    }

    if (addedCount > 0) {
      print addedMsg
    }

    if (deletedCount > 0) {
      print deletedMsg
    }
  }

  if (changesCount == 1) {
    if (updatedCount > 0) {
      print updatedMsg
    }

    if (addedCount > 0) {
      print addedMsg
    }

    if (deletedCount > 0) {
      print deletedMsg
    }
  }
}
')

if [ -z "${COMMIT_MSG}" ]
then
  echo "git-infer: Nothing added, updated or deleted"
  exit 1
fi

if [ "$TYPE" = "$all_tracked" ];then
  git add -u;
fi

if [ "$TYPE" = "$all_untracked" ];then
  git add .;
fi

git commit -m "${COMMIT_MSG}"
