#!/usr/bin/env bash
COMMIT_MSG=$(git diff --staged --name-status | awk '
BEGIN {
  updatedCount = 0;
  addedCount = 0;
  deletedCount = 0;
}

$1 == "M" {
  updated[updatedCount] = $2;
  updatedCount += 1
}

$1 == "A" {
  added[addedCount] = $2;
  addedCount += 1
}

$1 == "D" {
  deleted[deletedCount] = $2;
  deletedCount += 1
}

END {
  if (updatedCount > 0) {
    updatedMsg = "";
    for (i = 0; i + 1 < updatedCount; i++) {
      updatedMsg = updatedMsg updated[i] ", "
    };
    updatedMsg = updatedMsg updated[updatedCount - 1]
    updatedMsg = "Update " updatedMsg
  }

  if (addedCount > 0) {
    addedMsg = "";
    for (i = 0; i + 1 < addedCount; i++) {
      addedMsg = addedMsg added[i] ", "
    };
    addedMsg = addedMsg added[addedCount - 1]
    addedMsg = "Add " addedMsg
  }

  if (deletedCount > 0) {
    deletedMsg = "";
    for (i = 0; i + 1 < deletedCount; i++) {
      deletedMsg = deletedMsg deleted[i] ", "
    };
    deletedMsg = deletedMsg deleted[deletedCount - 1]
    deletedMsg = "Delete " deletedMsg
  }

  if (updatedCount > 0) {
    print updatedMsg
  }
  if (addedCount > 0) {
    print addedMsg
  }
  if (deletedCount > 0) {
    print deletedMsg
  }
}
')

if [ -z "${COMMIT_MSG}" ]
then
  echo "git-infer: Nothing added, updated or deleted"
  exit 1
fi

git commit -m "${COMMIT_MSG}" "$@"
